CREATE TABLE reviews (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL DEFAULT 'Клиентка',
  text TEXT NOT NULL,
  stars INTEGER NOT NULL DEFAULT 5,
  approved BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);